#!/usr/bin/env python3
"""Validate release identity and generate compile-time build constants."""
import re
import sys
from pathlib import Path

version, channel, target = sys.argv[1:]
core = r"(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
pattern = core if channel == "stable" else core + r"-beta\.[1-9][0-9]*"
if channel not in ("stable", "beta") or not re.fullmatch(pattern, version):
    sys.exit(f"Invalid {channel} release version: {version}")
if target != "--validate-only":
    Path(target).write_text(
        "// Generated by Scripts/build-app.sh.\n"
        "enum BuildInfo {\n"
        f"    static let channel: AppChannel = .{channel}\n"
        f'    static let version = "{version}"\n'
        "}\n"
    )
