name: Release Stable
on:
  push:
    tags: ["v[0-9]*.[0-9]*.[0-9]*"]
permissions:
  contents: write
  actions: read
jobs:
  release:
    if: ${{ !contains(github.ref_name, '-') }}
    uses: ./.github/workflows/release-common.yml
    with:
      channel: stable
    secrets: inherit
